const agriZen = {
  name: 'agriZen',
  tokens: {
    primaryBg: '#f4f7f0',
    primaryText: '#2c3e2e',
    secondaryText: '#5c6b5d',
    panelBg: '#ffffff',
    panelHeaderBg: '#e8efe6',
    panelBorder: '#a3b8a6',
    panelHeaderText: '#2c3e2e',
    headerGradTop: '#f4f7f0',
    headerGradBottom: '#e8efe6',
    toolbarGradTop: '#f4f7f0',
    toolbarGradBottom: '#e8efe6',
    surfaceBg: '#e8efe6',
    surfaceBorder: '#a3b8a6',
    toolbarBg: '#e8efe6',
    toolbarBorder: '#a3b8a6',
    fieldBg: '#ffffff',
    fieldText: '#2c3e2e',
    fieldBorder: '#a3b8a6',
    fieldBorderHover: '#7a967d',
    fieldBorderFocus: '#4a6b4e',
    fieldDisabledBg: '#f4f7f0',
    selectionBg: '#cde0cc',
    selectionText: '#2c3e2e',
    hoverBg: '#dce6da',
    activeBg: '#cde0cc',
    successBg: '#d4edda',
    successText: '#155724',
    warningBg: '#fff3cd',
    warningText: '#856404',
    errorBg: '#f8d7da',
    errorText: '#721c24',
    infoBg: '#d1ecf1',
    infoText: '#0c5460',
    highlightBg: '#4a6b4e',
    highlightText: '#ffffff',
    shadowSm: '0 1px 3px rgba(44, 62, 46, 0.1)',
    shadowMd: '0 4px 10px rgba(44, 62, 46, 0.1)',
    // Tokens adicionales
    cardBg: '#ffffff',
    cardBorder: '#a3b8a6',
    modalBg: '#ffffff',
    modalHeaderBg: '#e8efe6',
    modalOverlay: 'rgba(44, 62, 46, 0.4)',
    inputBg: '#ffffff',
    tableBg: '#ffffff',
    tableHeaderBg: '#e8efe6',
    tableRowHover: '#f4f7f0',
    tableRowAlt: '#f9fbf8',
    divider: '#a3b8a6',
    sidebarBg: '#e8efe6',
    sidebarHover: '#dce6da',
    sidebarActive: '#cde0cc',
    buttonText: '#ffffff',
  },
}

export default agriZen
