const blue = {
  name: 'blue',
  tokens: {
    primaryBg: '#dfe8f6',
    primaryText: '#1f2d3d',
    secondaryText: '#475569',
    panelBg: '#ffffff',
    panelHeaderBg: '#99bbe8',
    panelBorder: '#8db2e3',
    panelHeaderText: '#0f1f33',
    headerGradTop: '#dbe6f7',
    headerGradBottom: '#c3d6f0',
    toolbarGradTop: '#dbe6f7',
    toolbarGradBottom: '#c3d6f0',
    surfaceBg: '#f5f7fb',
    surfaceBorder: '#c2d3ef',
    toolbarBg: '#99bbe8',
    toolbarBorder: '#8db2e3',
    fieldBg: '#ffffff',
    fieldText: '#1f2d3d',
    fieldBorder: '#8db2e3',
    fieldBorderHover: '#7299d1',
    fieldBorderFocus: '#3a6ea5',
    fieldDisabledBg: '#e3eaf5',
    selectionBg: '#c5d9f1',
    selectionText: '#0f1f33',
    hoverBg: '#e4ebf7',
    activeBg: '#c7d7f2',
    successBg: '#dff3d8',
    successText: '#245c1c',
    warningBg: '#fff2cc',
    warningText: '#7a5b00',
    errorBg: '#fde2e1',
    errorText: '#7a1f1f',
    infoBg: '#e2ecfb',
    infoText: '#1e4b87',
    highlightBg: '#1e3a5f',
    highlightText: '#ffffff',
    shadowSm: '0 1px 2px rgba(0, 0, 0, 0.08)',
    shadowMd: '0 3px 8px rgba(0, 0, 0, 0.12)',
    // Tokens adicionales
    cardBg: '#ffffff',
    cardBorder: '#e5e7eb',
    modalBg: '#ffffff',
    modalHeaderBg: '#f8fafc',
    modalOverlay: 'rgba(0, 0, 0, 0.5)',
    inputBg: '#ffffff',
    tableBg: '#ffffff',
    tableHeaderBg: '#f1f5f9',
    tableRowHover: '#f8fafc',
    tableRowAlt: '#f9fafb',
    divider: '#e5e7eb',
    sidebarBg: '#f8fafc',
    sidebarHover: '#e2e8f0',
    sidebarActive: '#dbeafe',
    buttonText: '#ffffff',
  },
}

export default blue
