const earth = {
    name: 'earth',
    tokens: {
        primaryBg: '#efebe2',
        primaryText: '#3e2c1c',
        secondaryText: '#7a6652',
        panelBg: '#ffffff',
        panelHeaderBg: '#c4a882',
        panelBorder: '#b39770',
        panelHeaderText: '#2a1c0e',
        headerGradTop: '#e4dcd0',
        headerGradBottom: '#d4c8b4',
        toolbarGradTop: '#e4dcd0',
        toolbarGradBottom: '#d4c8b4',
        surfaceBg: '#f8f5ef',
        surfaceBorder: '#d5c9b5',
        toolbarBg: '#c4a882',
        toolbarBorder: '#b39770',
        fieldBg: '#ffffff',
        fieldText: '#3e2c1c',
        fieldBorder: '#b39770',
        fieldBorderHover: '#9e8259',
        fieldBorderFocus: '#8b6d3f',
        fieldDisabledBg: '#ede8df',
        selectionBg: '#d5c9b5',
        selectionText: '#2a1c0e',
        hoverBg: '#e4dcd0',
        activeBg: '#cec0a8',
        successBg: '#e4f0d7',
        successText: '#2f5a1f',
        warningBg: '#fff2cc',
        warningText: '#7a5b00',
        errorBg: '#f5dfdf',
        errorText: '#742222',
        infoBg: '#efebe2',
        infoText: '#5e4428',
        highlightBg: '#5e4428',
        highlightText: '#ffffff',
        shadowSm: '0 1px 2px rgba(0, 0, 0, 0.08)',
        shadowMd: '0 3px 8px rgba(0, 0, 0, 0.12)',
        // Tokens adicionales
        cardBg: '#ffffff',
        cardBorder: '#e8e0d4',
        modalBg: '#ffffff',
        modalHeaderBg: '#faf7f3',
        modalOverlay: 'rgba(0, 0, 0, 0.5)',
        inputBg: '#ffffff',
        tableBg: '#ffffff',
        tableHeaderBg: '#f4f0e8',
        tableRowHover: '#faf7f3',
        tableRowAlt: '#fbf9f5',
        divider: '#e8e0d4',
        sidebarBg: '#faf7f3',
        sidebarHover: '#e4dcd0',
        sidebarActive: '#d5c9b5',
        buttonText: '#ffffff',
    },
}

export default earth
