const gray = {
  name: 'gray',
  tokens: {
    primaryBg: '#e5e5e5',
    primaryText: '#1f1f1f',
    secondaryText: '#555555',
    panelBg: '#ffffff',
    panelHeaderBg: '#c4c4c4',
    panelBorder: '#b3b3b3',
    panelHeaderText: '#0f0f0f',
    headerGradTop: '#d8d8d8',
    headerGradBottom: '#c4c4c4',
    toolbarGradTop: '#d8d8d8',
    toolbarGradBottom: '#c4c4c4',
    surfaceBg: '#f2f2f2',
    surfaceBorder: '#cfcfcf',
    toolbarBg: '#c4c4c4',
    toolbarBorder: '#b3b3b3',
    fieldBg: '#ffffff',
    fieldText: '#1f1f1f',
    fieldBorder: '#b3b3b3',
    fieldBorderHover: '#999999',
    fieldBorderFocus: '#6b6b6b',
    fieldDisabledBg: '#ededed',
    selectionBg: '#cfcfcf',
    selectionText: '#111111',
    hoverBg: '#d8d8d8',
    activeBg: '#c0c0c0',
    successBg: '#e3f4df',
    successText: '#2f5f23',
    warningBg: '#fff3d6',
    warningText: '#7a5f00',
    errorBg: '#f6dada',
    errorText: '#742222',
    infoBg: '#e5e8ed',
    infoText: '#2f3640',
    highlightBg: '#3d3d3d',
    highlightText: '#ffffff',
    shadowSm: '0 1px 2px rgba(0, 0, 0, 0.08)',
    shadowMd: '0 3px 8px rgba(0, 0, 0, 0.12)',
    // Tokens adicionales
    cardBg: '#ffffff',
    cardBorder: '#e5e7eb',
    modalBg: '#ffffff',
    modalHeaderBg: '#f8fafc',
    modalOverlay: 'rgba(0, 0, 0, 0.5)',
    inputBg: '#ffffff',
    tableBg: '#ffffff',
    tableHeaderBg: '#f1f5f9',
    tableRowHover: '#f8fafc',
    tableRowAlt: '#f9fafb',
    divider: '#e5e7eb',
    sidebarBg: '#f8fafc',
    sidebarHover: '#e2e8f0',
    sidebarActive: '#e5e7eb',
    buttonText: '#ffffff',
  },
}

export default gray
