const kaizen = {
    name: 'kaizen',
    tokens: {
        primaryBg: '#f9f3f1',
        primaryText: '#3b2820',
        secondaryText: '#7a6560',
        panelBg: '#ffffff',
        panelHeaderBg: '#e8a99a',
        panelBorder: '#dca090',
        panelHeaderText: '#3b1810',
        headerGradTop: '#f5ddd6',
        headerGradBottom: '#ecc7bc',
        toolbarGradTop: '#f5ddd6',
        toolbarGradBottom: '#ecc7bc',
        surfaceBg: '#fdf7f5',
        surfaceBorder: '#e8ccc4',
        toolbarBg: '#e8a99a',
        toolbarBorder: '#dca090',
        fieldBg: '#ffffff',
        fieldText: '#3b2820',
        fieldBorder: '#dca090',
        fieldBorderHover: '#cc8877',
        fieldBorderFocus: '#c26650',
        fieldDisabledBg: '#f5ebe7',
        selectionBg: '#f0d0c6',
        selectionText: '#3b1810',
        hoverBg: '#f5e3dc',
        activeBg: '#ecc7bc',
        successBg: '#e4f0d7',
        successText: '#2f5a1f',
        warningBg: '#fff2cc',
        warningText: '#7a5b00',
        errorBg: '#fde2e1',
        errorText: '#7a1f1f',
        infoBg: '#f9f3f1',
        infoText: '#8c4030',
        highlightBg: '#c26650',
        highlightText: '#ffffff',
        shadowSm: '0 1px 2px rgba(0, 0, 0, 0.06)',
        shadowMd: '0 3px 8px rgba(0, 0, 0, 0.10)',
        // Tokens adicionales
        cardBg: '#ffffff',
        cardBorder: '#efe0db',
        modalBg: '#ffffff',
        modalHeaderBg: '#fdf7f5',
        modalOverlay: 'rgba(0, 0, 0, 0.45)',
        inputBg: '#ffffff',
        tableBg: '#ffffff',
        tableHeaderBg: '#faf0ec',
        tableRowHover: '#fdf7f5',
        tableRowAlt: '#fef9f7',
        divider: '#efe0db',
        sidebarBg: '#fdf7f5',
        sidebarHover: '#f5ddd6',
        sidebarActive: '#f0d0c6',
        buttonText: '#ffffff',
    },
}

export default kaizen
