const nordicMinimal = {
  name: 'nordicMinimal',
  tokens: {
    primaryBg: '#f0f4f8',
    primaryText: '#2d3748',
    secondaryText: '#64748b',
    panelBg: '#ffffff',
    panelHeaderBg: '#e2e8f0',
    panelBorder: '#cbd5e1',
    panelHeaderText: '#1e293b',
    headerGradTop: '#f8fafc',
    headerGradBottom: '#e2e8f0',
    toolbarGradTop: '#f8fafc',
    toolbarGradBottom: '#e2e8f0',
    surfaceBg: '#f1f5f9',
    surfaceBorder: '#cbd5e1',
    toolbarBg: '#e2e8f0',
    toolbarBorder: '#cbd5e1',
    fieldBg: '#ffffff',
    fieldText: '#2d3748',
    fieldBorder: '#cbd5e1',
    fieldBorderHover: '#94a3b8',
    fieldBorderFocus: '#475569',
    fieldDisabledBg: '#f1f5f9',
    selectionBg: '#cbd5e1',
    selectionText: '#1e293b',
    hoverBg: '#e2e8f0',
    activeBg: '#cbd5e1',
    successBg: '#dcfce7',
    successText: '#166534',
    warningBg: '#fef3c7',
    warningText: '#92400e',
    errorBg: '#fee2e2',
    errorText: '#991b1b',
    infoBg: '#e0f2fe',
    infoText: '#075985',
    highlightBg: '#475569',
    highlightText: '#ffffff',
    shadowSm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    shadowMd: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    // Tokens adicionales
    cardBg: '#ffffff',
    cardBorder: '#e2e8f0',
    modalBg: '#ffffff',
    modalHeaderBg: '#f8fafc',
    modalOverlay: 'rgba(15, 23, 42, 0.2)',
    inputBg: '#ffffff',
    tableBg: '#ffffff',
    tableHeaderBg: '#f1f5f9',
    tableRowHover: '#f8fafc',
    tableRowAlt: '#f9fafb',
    divider: '#e2e8f0',
    sidebarBg: '#ffffff',
    sidebarHover: '#f1f5f9',
    sidebarActive: '#e2e8f0',
    buttonText: '#ffffff',
  },
}

export default nordicMinimal
