const oceanicFlow = {
  name: 'oceanicFlow',
  tokens: {
    primaryBg: '#e0f7fa',
    primaryText: '#006064',
    secondaryText: '#00838f',
    panelBg: '#ffffff',
    panelHeaderBg: '#b2ebf2',
    panelBorder: '#4dd0e1',
    panelHeaderText: '#006064',
    headerGradTop: '#e0f7fa',
    headerGradBottom: '#b2ebf2',
    toolbarGradTop: '#e0f7fa',
    toolbarGradBottom: '#b2ebf2',
    surfaceBg: '#e0f7fa',
    surfaceBorder: '#4dd0e1',
    toolbarBg: '#b2ebf2',
    toolbarBorder: '#4dd0e1',
    fieldBg: '#ffffff',
    fieldText: '#006064',
    fieldBorder: '#4dd0e1',
    fieldBorderHover: '#00bcd4',
    fieldBorderFocus: '#0097a7',
    fieldDisabledBg: '#e0f7fa',
    selectionBg: '#80deea',
    selectionText: '#006064',
    hoverBg: '#b2ebf2',
    activeBg: '#80deea',
    successBg: '#e0f2f1',
    successText: '#004d40',
    warningBg: '#fff8e1',
    warningText: '#ff6f00',
    errorBg: '#ffebee',
    errorText: '#b71c1c',
    infoBg: '#e1f5fe',
    infoText: '#01579b',
    highlightBg: '#00bcd4',
    highlightText: '#ffffff',
    shadowSm: '0 2px 4px rgba(0, 96, 100, 0.1)',
    shadowMd: '0 4px 8px rgba(0, 96, 100, 0.2)',
    // Tokens adicionales
    cardBg: '#ffffff',
    cardBorder: '#4dd0e1',
    modalBg: '#ffffff',
    modalHeaderBg: '#b2ebf2',
    modalOverlay: 'rgba(0, 96, 100, 0.3)',
    inputBg: '#ffffff',
    tableBg: '#ffffff',
    tableHeaderBg: '#e0f7fa',
    tableRowHover: '#b2ebf2',
    tableRowAlt: '#e0f7fa',
    divider: '#4dd0e1',
    sidebarBg: '#e0f7fa',
    sidebarHover: '#b2ebf2',
    sidebarActive: '#80deea',
    buttonText: '#ffffff',
  },
}

export default oceanicFlow
