const olive = {
  name: 'olive',
  tokens: {
    primaryBg: '#e7ebd3',
    primaryText: '#252b1a',
    secondaryText: '#5c6645',
    panelBg: '#ffffff',
    panelHeaderBg: '#c2c99a',
    panelBorder: '#aab37a',
    panelHeaderText: '#1d240f',
    headerGradTop: '#dfe6c4',
    headerGradBottom: '#c9d19f',
    toolbarGradTop: '#dfe6c4',
    toolbarGradBottom: '#c9d19f',
    surfaceBg: '#f3f5e4',
    surfaceBorder: '#cdd6aa',
    toolbarBg: '#c2c99a',
    toolbarBorder: '#aab37a',
    fieldBg: '#ffffff',
    fieldText: '#252b1a',
    fieldBorder: '#aab37a',
    fieldBorderHover: '#8e9a5e',
    fieldBorderFocus: '#7c8a45',
    fieldDisabledBg: '#e4e8d3',
    selectionBg: '#cfd7ae',
    selectionText: '#1d240f',
    hoverBg: '#d9dfc0',
    activeBg: '#c7d399',
    successBg: '#dff1d5',
    successText: '#2f5f23',
    warningBg: '#fff2cc',
    warningText: '#7a5b00',
    errorBg: '#f5dfdf',
    errorText: '#742222',
    infoBg: '#e7efd9',
    infoText: '#2d3b1d',
    highlightBg: '#3d4a2a',
    highlightText: '#ffffff',
    shadowSm: '0 1px 2px rgba(0, 0, 0, 0.08)',
    shadowMd: '0 3px 8px rgba(0, 0, 0, 0.12)',
    // Tokens adicionales
    cardBg: '#ffffff',
    cardBorder: '#e5e7eb',
    modalBg: '#ffffff',
    modalHeaderBg: '#f8fafc',
    modalOverlay: 'rgba(0, 0, 0, 0.5)',
    inputBg: '#ffffff',
    tableBg: '#ffffff',
    tableHeaderBg: '#f1f5f9',
    tableRowHover: '#f8fafc',
    tableRowAlt: '#f9fafb',
    divider: '#e5e7eb',
    sidebarBg: '#f8fafc',
    sidebarHover: '#dfe6c4',
    sidebarActive: '#cfd7ae',
    buttonText: '#ffffff',
  },
}

export default olive
