const paperStack = {
  name: 'paperStack',
  tokens: {
    primaryBg: '#fdfbf7',
    primaryText: '#2b2b2b',
    secondaryText: '#555555',
    panelBg: '#ffffff',
    panelHeaderBg: '#f4f1ea',
    panelBorder: '#d3d3d3',
    panelHeaderText: '#2b2b2b',
    headerGradTop: '#fdfbf7',
    headerGradBottom: '#f4f1ea',
    toolbarGradTop: '#fdfbf7',
    toolbarGradBottom: '#f4f1ea',
    surfaceBg: '#f9f7f1',
    surfaceBorder: '#d3d3d3',
    toolbarBg: '#f4f1ea',
    toolbarBorder: '#d3d3d3',
    fieldBg: '#ffffff',
    fieldText: '#2b2b2b',
    fieldBorder: '#888888',
    fieldBorderHover: '#000000',
    fieldBorderFocus: '#000000',
    fieldDisabledBg: '#f4f1ea',
    selectionBg: '#fff2cc', // Amarillo post-it
    selectionText: '#000000',
    hoverBg: '#f0ede6',
    activeBg: '#e6e2d8',
    successBg: '#e6f4ea',
    successText: '#1e7e34',
    warningBg: '#fff3cd',
    warningText: '#856404',
    errorBg: '#f8d7da',
    errorText: '#721c24',
    infoBg: '#d1ecf1',
    infoText: '#0c5460',
    highlightBg: '#2b2b2b',
    highlightText: '#ffffff',
    shadowSm: '2px 2px 0px rgba(0, 0, 0, 0.1)',
    shadowMd: '4px 4px 0px rgba(0, 0, 0, 0.1)',
    // Tokens adicionales
    cardBg: '#ffffff',
    cardBorder: '#d3d3d3',
    modalBg: '#ffffff',
    modalHeaderBg: '#f9f7f1',
    modalOverlay: 'rgba(0, 0, 0, 0.3)',
    inputBg: '#ffffff',
    tableBg: '#ffffff',
    tableHeaderBg: '#f4f1ea',
    tableRowHover: '#fff2cc',
    tableRowAlt: '#fdfbf7',
    divider: '#d3d3d3',
    sidebarBg: '#f4f1ea',
    sidebarHover: '#e6e2d8',
    sidebarActive: '#d3d3d3',
    buttonText: '#ffffff',
  },
}

export default paperStack
