const purple = {
    name: 'purple',
    tokens: {
        primaryBg: '#ede5f6',
        primaryText: '#2d1b4e',
        secondaryText: '#6b5b7b',
        panelBg: '#ffffff',
        panelHeaderBg: '#b39ddb',
        panelBorder: '#9c85c9',
        panelHeaderText: '#1a0e33',
        headerGradTop: '#e1d5f0',
        headerGradBottom: '#cdbde5',
        toolbarGradTop: '#e1d5f0',
        toolbarGradBottom: '#cdbde5',
        surfaceBg: '#f7f3fb',
        surfaceBorder: '#d1c4e9',
        toolbarBg: '#b39ddb',
        toolbarBorder: '#9c85c9',
        fieldBg: '#ffffff',
        fieldText: '#2d1b4e',
        fieldBorder: '#9c85c9',
        fieldBorderHover: '#8167b8',
        fieldBorderFocus: '#6a42a0',
        fieldDisabledBg: '#ece4f5',
        selectionBg: '#d1c4e9',
        selectionText: '#1a0e33',
        hoverBg: '#e8ddf4',
        activeBg: '#c9b8e4',
        successBg: '#dff3d8',
        successText: '#245c1c',
        warningBg: '#fff2cc',
        warningText: '#7a5b00',
        errorBg: '#fde2e1',
        errorText: '#7a1f1f',
        infoBg: '#ede5f6',
        infoText: '#4a2d7a',
        highlightBg: '#4a2d7a',
        highlightText: '#ffffff',
        shadowSm: '0 1px 2px rgba(0, 0, 0, 0.08)',
        shadowMd: '0 3px 8px rgba(0, 0, 0, 0.12)',
        // Tokens adicionales
        cardBg: '#ffffff',
        cardBorder: '#e5e0ee',
        modalBg: '#ffffff',
        modalHeaderBg: '#f8f5fc',
        modalOverlay: 'rgba(0, 0, 0, 0.5)',
        inputBg: '#ffffff',
        tableBg: '#ffffff',
        tableHeaderBg: '#f3eff8',
        tableRowHover: '#f8f5fc',
        tableRowAlt: '#faf8fd',
        divider: '#e5e0ee',
        sidebarBg: '#f8f5fc',
        sidebarHover: '#e1d5f0',
        sidebarActive: '#d1c4e9',
        buttonText: '#ffffff',
    },
}

export default purple
