const rose = {
    name: 'rose',
    tokens: {
        primaryBg: '#fce4ec',
        primaryText: '#3d1a25',
        secondaryText: '#7a5060',
        panelBg: '#ffffff',
        panelHeaderBg: '#f48fb1',
        panelBorder: '#ef6c9a',
        panelHeaderText: '#2c0e1a',
        headerGradTop: '#f8d0dd',
        headerGradBottom: '#f1b8cc',
        toolbarGradTop: '#f8d0dd',
        toolbarGradBottom: '#f1b8cc',
        surfaceBg: '#fdf2f5',
        surfaceBorder: '#f3c0d3',
        toolbarBg: '#f48fb1',
        toolbarBorder: '#ef6c9a',
        fieldBg: '#ffffff',
        fieldText: '#3d1a25',
        fieldBorder: '#ef6c9a',
        fieldBorderHover: '#e84d82',
        fieldBorderFocus: '#d81b60',
        fieldDisabledBg: '#fbe3ea',
        selectionBg: '#f3c0d3',
        selectionText: '#2c0e1a',
        hoverBg: '#f8d0dd',
        activeBg: '#f0b0c8',
        successBg: '#dff3d8',
        successText: '#245c1c',
        warningBg: '#fff2cc',
        warningText: '#7a5b00',
        errorBg: '#fde2e1',
        errorText: '#7a1f1f',
        infoBg: '#fce4ec',
        infoText: '#880e4f',
        highlightBg: '#880e4f',
        highlightText: '#ffffff',
        shadowSm: '0 1px 2px rgba(0, 0, 0, 0.08)',
        shadowMd: '0 3px 8px rgba(0, 0, 0, 0.12)',
        // Tokens adicionales
        cardBg: '#ffffff',
        cardBorder: '#f0dce3',
        modalBg: '#ffffff',
        modalHeaderBg: '#fdf5f8',
        modalOverlay: 'rgba(0, 0, 0, 0.5)',
        inputBg: '#ffffff',
        tableBg: '#ffffff',
        tableHeaderBg: '#faecf0',
        tableRowHover: '#fdf5f8',
        tableRowAlt: '#fef8fa',
        divider: '#f0dce3',
        sidebarBg: '#fdf5f8',
        sidebarHover: '#f8d0dd',
        sidebarActive: '#f3c0d3',
        buttonText: '#ffffff',
    },
}

export default rose
