const teal = {
    name: 'teal',
    tokens: {
        primaryBg: '#e0f2f1',
        primaryText: '#1a3c3a',
        secondaryText: '#4f736e',
        panelBg: '#ffffff',
        panelHeaderBg: '#80cbc4',
        panelBorder: '#66bbb3',
        panelHeaderText: '#0d2622',
        headerGradTop: '#d4ede9',
        headerGradBottom: '#b2dfdb',
        toolbarGradTop: '#d4ede9',
        toolbarGradBottom: '#b2dfdb',
        surfaceBg: '#f0faf8',
        surfaceBorder: '#b2dfdb',
        toolbarBg: '#80cbc4',
        toolbarBorder: '#66bbb3',
        fieldBg: '#ffffff',
        fieldText: '#1a3c3a',
        fieldBorder: '#66bbb3',
        fieldBorderHover: '#4db6ac',
        fieldBorderFocus: '#00897b',
        fieldDisabledBg: '#e0f0ee',
        selectionBg: '#b2dfdb',
        selectionText: '#0d2622',
        hoverBg: '#d4ede9',
        activeBg: '#a7d8d2',
        successBg: '#dff3d8',
        successText: '#245c1c',
        warningBg: '#fff2cc',
        warningText: '#7a5b00',
        errorBg: '#fde2e1',
        errorText: '#7a1f1f',
        infoBg: '#e0f2f1',
        infoText: '#00695c',
        highlightBg: '#00695c',
        highlightText: '#ffffff',
        shadowSm: '0 1px 2px rgba(0, 0, 0, 0.08)',
        shadowMd: '0 3px 8px rgba(0, 0, 0, 0.12)',
        // Tokens adicionales
        cardBg: '#ffffff',
        cardBorder: '#dce9e7',
        modalBg: '#ffffff',
        modalHeaderBg: '#f5fbfa',
        modalOverlay: 'rgba(0, 0, 0, 0.5)',
        inputBg: '#ffffff',
        tableBg: '#ffffff',
        tableHeaderBg: '#ecf6f4',
        tableRowHover: '#f5fbfa',
        tableRowAlt: '#f7fcfb',
        divider: '#dce9e7',
        sidebarBg: '#f5fbfa',
        sidebarHover: '#d4ede9',
        sidebarActive: '#b2dfdb',
        buttonText: '#ffffff',
    },
}

export default teal
